### PR TITLE
Add incremental argument to CreateImageFromMachine

### PR DESCRIPTION
**Pull request by blackwood821**
Currently there is no way to create a full image because `CreateImageFromMachine` is hard-coded to always generate incremental images (https://github.com/joyent/sdc-cloudapi/issues/71).

### CODE REVIEW

**Comment by twhiteman** [comment]
Looks good, just needs a couple of additions:
1) bump the package.json version (e.g. to "9.15.0")
2) add a "9.15.0" change entry to the docs/index.md (see "The section describes API changes in CloudAPI versions.")
3) add documentation to CreateImageFromMachine (incremental boolean - defaults to true)

**Comment by blackwood821** [comment]
@twhiteman Thanks for the pointers. I committed the requested changes. Do I need to do anything to update the documentation on https://apidocs.joyent.com/cloudapi/#CreateImageFromMachine or does that come from index.md in this repo?

**Review by twhiteman — APPROVED** [review]
LGTM.

The CloudAPI documentation gets (manually) generated from this file and uploaded to the site.

**Comment by twhiteman** [comment]
Fixes #71

**Pull request merged**
