### PR TITLE
TRITON-853 cloudapi should allow creation of instances with delegated datasets

### PR DESCRIPTION
**Pull request by timfoster**

### CODE REVIEW

**Comment by timfoster** [comment]
Sorry for the delay, I'm not at all familiar with the test code, but it looks like we'd be looking for a new test in `test/machines.test.js` (I wasn't sure whether I should be adding a new machines.[version].js instead)

What's the convention for having test code modify the triton instance? Specifically, we don't currently have a sapi client in the test setup, and I wasn't sure whether that was intentional?

I had started down the path of adding it, e.g.

```
timf@iorangi-eth0 (prr-TRITON-853) git diff
diff --git a/test/common.js b/test/common.js
index f316b4f..ccb8677 100644
--- a/test/common.js
+++ b/test/common.js
@@ -32,6 +32,7 @@ var IMGAPI = require('sdc-clients').IMGAPI;
 var PAPI = require('sdc-clients').PAPI;
 var MAHI = require('mahi');
 var VOLAPI = require('sdc-clients').VOLAPI;
+var SAPI = require('sdc-clients').SAPI;

 var apertureConfig = require('aperture-config').config;

@@ -190,6 +191,18 @@ function _imgapi() {
     });
 }

+function _sapi() {
+    return new SAPI({
+        url: process.env.SAPI_URL || CONFIG.sapi.url || 'http://10.99.99.31',
+        retry: {
+            retries: 1,
+            minTimeout: 1000
+        },
+        log: LOG,
+        agent: false
+    });
+}
+
 function _joyentImgapi() {
     return new IMGAPI({
         url: 'https://images.joyent.com/',
@@ -523,6 +536,7 @@ function setupClient(version, serverUrl, user, keyId, keyPath, parentAcc, cb) {
     client.papi   = _papi();
     client.mahi   = _mahi();
     client.ufds   = _ufds();
+    client.sapi   = _sapi();
     if (CONFIG.experimental_cloudapi_nfs_shared_volumes === true) {
         client.volapi = _volapi();
     }
```

but I'm not sure if that's the right approach. Should I just assume that the instance I'm talking to has delegated datasets disabled?

**Comment by twhiteman** [comment]
There are methods to obtain CloudAPI (SAPI) already, e.g. see `experimental_cloudapi_nfs_shared_volumes`:
https://github.com/joyent/sdc-cloudapi/blob/master/test/volumes-automount.test.js#L50

I really don't understand the `machines.[version].js`, but @kusor probably does.

It might even be possible to add `delegate_dataset` to an existing (general) VM provision test - I'd be fine with that.

**Comment by twhiteman** [comment]
Then after, we can enable `CloudAPI.experimental_cloudapi_delegate_dataset` setting in nightly setup.

**Comment by bahamat** [comment]
Ok, I added a test to this PR, as well as bumped the version number due to a recent conflicting version number bump.

This is working for me, but I'm getting intermittent errors on other tests that I think are all just due to coal being resource starved.

Tested both with `experimental_cloudapi_delegate_dataset` set `true` (tests pass), and `false` (tests are skipped).

**Comment by twhiteman** [comment]
I changed a few things around in the PR:

1. I changed the delegate_dataset property from "on|off" to true|false (to be consistent with what VMAPI uses).
2. I had to change the way delegate_dataset is reported in the GetMachine call (there is no property - must inspect the datasets array)
3. updated test case to ensure createMachine failure when dataset provisioning is disabled
4. added documentation

**Comment by bahamat** [comment]
See also joyent/node-triton#301

**Pull request merged**
